version: "3.8"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
    volumes:
        - type: volume
          source: esdata
          target: /usr/share/elasticsearch/data
          tmpfs:
            size: 100000

volumes:
  esdata:
    external: true