version: "3.3"
services:
  elasticsearch:
    container_name: es-container
    hostname: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  essearchservice:
    container_name: essearch
    build:
      context: ./es_search_service
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
    environment:
      - ES_HOST=http://es-container:9200
    ports:
      - 8087:8087

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - "./pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "vfifif"
      PGDATA: "/var/lib/postgresql/data/edudata"

volumes:
  esdata:
    external: true
  pgdata:
